<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-32GN0UI0" failures="1" tests="1" name="Test" time="0.042" errors="0" timestamp="18 Nov 2022 15:17:00 GMT">
  <testcase classname="test.PhpTravels.TestNGAnnotations" name="test" time="0.013">
    <failure type="java.lang.AssertionError" message="value of i is not equal to 3 expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: value of i is not equal to 3 expected [2] but found [3]
	at test.PhpTravels.TestNGAnnotations.test(TestNGAnnotations.java:40)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Test -->
